/**
 * Expanded Asset Generation Script - 500+ Assets from COMPREHENSIVE-ASSET-REQUIREMENTS.md
 * Generates PNG images with NO TEXT and detailed prompts using Gemini 2.5 Flash Image Preview
 */

require('dotenv').config({ path: require('path').join(__dirname, '../../.env') });

const { GoogleGenerativeAI } = require('@google/generative-ai');
const fs = require('fs');
const path = require('path');

class ExpandedAssetGenerator {
  constructor() {
    const apiKey = process.env.GOOGLE_GEMINI_API_KEY || process.env.EXPO_PUBLIC_GEMINI_API_KEY;
    if (!apiKey) {
      throw new Error('GOOGLE_GEMINI_API_KEY or EXPO_PUBLIC_GEMINI_API_KEY environment variable is required');
    }
    
    this.genAI = new GoogleGenerativeAI(apiKey);
    this.assetsBasePath = path.join(__dirname, '../assets');
    this.generated = [];
    this.failed = [];
    
    console.log('🎨 Expanded Asset Generator initialized with Gemini 2.5 Flash Image Preview');
    console.log(`📁 Assets will be saved to: ${this.assetsBasePath}`);
    console.log('⚠️  CRITICAL: NO TEXT will be included on any images');
  }

  /**
   * Generate a single asset using Gemini 2.5 Flash Image Preview with NO TEXT
   */
  async generateAsset(spec) {
    try {
      console.log(`\\n🎯 Generating: ${spec.name}`);
      console.log(`📋 ${spec.description}`);
      console.log(`📐 Size: ${spec.width}x${spec.height}px`);
      console.log(`❌ NO TEXT: Visual elements only`);
      
      const model = this.genAI.getGenerativeModel({ 
        model: "gemini-2.5-flash-image-preview",
        generationConfig: {
          temperature: 0.7,
          topK: 40,
          topP: 0.9,
        }
      });

      // Create detailed prompt with NO TEXT enforcement
      const detailedPrompt = this.createNoTextPrompt(spec);
      console.log(`🤖 AI Prompt: ${detailedPrompt.substring(0, 100)}...`);

      // Generate image using Gemini
      const result = await model.generateContent([detailedPrompt]);
      const response = await result.response;
      
      // Extract the generated image
      const candidates = response.candidates;
      if (!candidates || candidates.length === 0) {
        throw new Error('No image generated by Gemini');
      }
      
      // Get the first candidate (image)
      const candidate = candidates[0];
      let base64Data = '';
      
      // Handle different response formats
      if (candidate.content && candidate.content.parts) {
        for (const part of candidate.content.parts) {
          if (part.inlineData && part.inlineData.mimeType?.startsWith('image/')) {
            base64Data = part.inlineData.data;
            break;
          }
        }
      }
      
      if (!base64Data) {
        console.warn(`⚠️ No image data generated for ${spec.name}, creating specification instead`);
        return await this.createSpecificationFile(spec, detailedPrompt);
      }
      
      // Save the generated image
      const filePath = this.getAssetPath(spec);
      const dir = path.dirname(filePath);
      if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
      }
      
      // Convert base64 to buffer and save as PNG
      const imageBuffer = Buffer.from(base64Data, 'base64');
      fs.writeFileSync(filePath, imageBuffer);
      
      console.log(`✅ PNG image saved (NO TEXT): ${filePath}`);
      this.generated.push(spec.name);
      return true;

    } catch (error) {
      console.error(`❌ Failed to generate ${spec.name}:`, error.message || error);
      
      // Fallback: create specification file
      console.log(`📋 Creating specification file as fallback for ${spec.name}`);
      const success = await this.createSpecificationFile(spec, this.createNoTextPrompt(spec));
      if (!success) {
        this.failed.push(spec.name);
      }
      return success;
    }
  }

  /**
   * Create detailed prompt with NO TEXT enforcement
   */
  createNoTextPrompt(spec) {
    let prompt = `Create a professional ${spec.description} for the Compozit Vision interior design mobile application.

CRITICAL REQUIREMENTS - NO TEXT OR LABELS:
- ABSOLUTELY NO TEXT, LETTERS, WORDS, OR LABELS anywhere in the image
- PURELY VISUAL representation only
- NO typography, captions, or written elements
- Visual elements ONLY

ASSET DETAILS:
- Name: ${spec.name}
- Purpose: ${spec.goal}
- Emotion/Feel: ${spec.emotion}
- Style: ${spec.style || 'Modern, professional, sophisticated'}
- Category: ${spec.category}

VISUAL REQUIREMENTS:
- Dimensions: ${spec.width}x${spec.height} pixels
- Primary Colors: #C9A98C (warm beige), #B9906F (brown), #FDFBF7 (cream background)
- Quality: High-resolution, professional grade
- Format: Optimized for mobile app interface
- Background: ${spec.backgroundType || 'Transparent or clean background'}

SPECIFIC CONTENT:
${spec.content || spec.prompt}

STYLE GUIDELINES:
- Premium, luxury design aesthetic
- Clean, modern, sophisticated look
- Brand-consistent color palette
- Mobile-optimized clarity and readability
- Professional ${spec.category === 'icon' ? 'icon' : 'photography/design'} quality
- NO sepia or vintage filters unless specifically for style
- Bright, clear, natural presentation

NO TEXT ENFORCEMENT:
- Verify NO text appears anywhere in the image
- Use only visual symbols and imagery
- Represent concepts through visual elements only
- NO written words, labels, or typography

${spec.additionalRequirements || ''}

Generate a high-quality ${spec.type} image that meets these specifications exactly, with ABSOLUTELY NO TEXT OR LABELS.`;

    return prompt;
  }

  /**
   * Create specification file as fallback
   */
  async createSpecificationFile(spec, prompt) {
    const specContent = {
      assetName: spec.name,
      type: spec.type,
      category: spec.category,
      subcategory: spec.subcategory,
      description: spec.description,
      goal: spec.goal,
      emotion: spec.emotion,
      dimensions: `${spec.width}x${spec.height}`,
      generationPrompt: prompt,
      noTextRequirement: "CRITICAL: This image must contain NO TEXT, LABELS, or typography",
      specifications: {
        width: spec.width,
        height: spec.height,
        format: spec.type,
        style: spec.style,
        colors: ['#C9A98C', '#B9906F', '#FDFBF7', '#1C1C1C'],
        priority: spec.priority,
        backgroundType: spec.backgroundType || 'transparent'
      },
      status: 'specification_generated',
      generatedAt: new Date().toISOString(),
      aiModel: 'gemini-2.5-flash-image-preview',
      nextSteps: [
        'Use the generation prompt with Gemini 2.5 Flash Image Preview',
        'ENSURE NO TEXT appears in the generated image',
        'Verify brand color compliance',
        'Optimize for mobile performance',
        'Test in actual app context'
      ]
    };

    const specPath = this.getAssetPath(spec).replace(`.${spec.type}`, '.spec.json');
    const dir = path.dirname(specPath);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }

    fs.writeFileSync(specPath, JSON.stringify(specContent, null, 2));
    console.log(`✅ Specification saved (NO TEXT): ${specPath}`);
    
    this.generated.push(spec.name);
    return true;
  }

  /**
   * Get the full file path for an asset
   */
  getAssetPath(spec) {
    let categoryPath = '';
    
    if (spec.category === 'icon') {
      categoryPath = `icons/${spec.subcategory || 'misc'}`;
    } else if (spec.category === 'image') {
      if (spec.subcategory?.includes('photography')) {
        categoryPath = `images/photography/${spec.subsubcategory || 'misc'}`;
      } else if (spec.subcategory?.includes('palette')) {
        categoryPath = `images/color-palettes`;
      } else if (spec.subcategory?.includes('illustration')) {
        categoryPath = `images/illustrations/${spec.subsubcategory || 'misc'}`;
      } else {
        categoryPath = `images/${spec.subcategory || 'misc'}`;
      }
    } else if (spec.category === 'animation') {
      categoryPath = `animations/${spec.type === 'mp4' ? 'videos' : 'lottie'}/${spec.subcategory || 'misc'}`;
    } else if (spec.category === 'brand') {
      categoryPath = `brand/${spec.subcategory || 'misc'}`;
    } else {
      categoryPath = spec.category || 'misc';
    }

    return path.join(this.assetsBasePath, categoryPath, `${spec.name}.${spec.type}`);
  }

  /**
   * Get all 500+ asset specifications from the expanded comprehensive requirements
   */
  getAllAssetSpecs() {
    return [
      // SPACE TYPE SELECTION (First Step)
      {
        name: 'exterior-spaces-icon',
        type: 'png',
        category: 'icon',
        subcategory: 'space-types',
        description: 'Outdoor/exterior spaces icon',
        goal: 'Visual distinction for exterior selection',
        emotion: 'Outdoor, fresh, natural',
        style: 'Clean architectural representation',
        content: 'House exterior with garden elements, outdoor living space',
        backgroundType: 'transparent',
        width: 96,
        height: 96,
        priority: 1
      },
      {
        name: 'interior-spaces-icon',
        type: 'png',
        category: 'icon',
        subcategory: 'space-types',
        description: 'Indoor/interior spaces icon',
        goal: 'Visual distinction for interior selection',
        emotion: 'Cozy, indoor, comfortable',
        style: 'Clean room representation',
        content: 'Room interior cutaway view with furniture',
        backgroundType: 'transparent',
        width: 96,
        height: 96,
        priority: 1
      },

      // RESIDENTIAL PROPERTY TYPES
      {
        name: 'single-family-house-icon',
        type: 'png',
        category: 'icon',
        subcategory: 'property-types',
        description: 'Single family home icon',
        goal: 'Represent single family house type',
        emotion: 'Traditional, family-oriented, stable',
        style: 'Clean architectural house silhouette',
        content: 'Simple house with pitched roof, front door, and windows',
        width: 80,
        height: 80,
        priority: 1
      },
      {
        name: 'townhouse-icon',
        type: 'png',
        category: 'icon',
        subcategory: 'property-types',
        description: 'Townhouse/rowhouse icon',
        goal: 'Represent townhouse property type',
        emotion: 'Urban, connected, community',
        style: 'Connected housing units',
        content: 'Multiple connected houses in a row',
        width: 80,
        height: 80,
        priority: 1
      },
      {
        name: 'villa-icon',
        type: 'png',
        category: 'icon',
        subcategory: 'property-types',
        description: 'Luxury villa icon',
        goal: 'Represent luxury villa type',
        emotion: 'Luxury, elegant, spacious',
        style: 'Elegant large house with distinctive features',
        content: 'Large house with columns or distinctive architectural elements',
        width: 80,
        height: 80,
        priority: 1
      },
      {
        name: 'apartment-icon',
        type: 'png',
        category: 'icon',
        subcategory: 'property-types',
        description: 'Apartment building icon',
        goal: 'Represent apartment living',
        emotion: 'Urban, modern, efficient',
        style: 'Multi-story building representation',
        content: 'Multi-story building with multiple units/windows',
        width: 80,
        height: 80,
        priority: 1
      },
      {
        name: 'loft-apartment-icon',
        type: 'png',
        category: 'icon',
        subcategory: 'property-types',
        description: 'Loft apartment icon',
        goal: 'Represent loft living space',
        emotion: 'Industrial, open, creative',
        style: 'Open space with industrial elements',
        content: 'Open space with high ceilings and large windows',
        width: 80,
        height: 80,
        priority: 1
      },
      {
        name: 'tiny-house-icon',
        type: 'png',
        category: 'icon',
        subcategory: 'property-types',
        description: 'Tiny house icon',
        goal: 'Represent tiny house living',
        emotion: 'Minimalist, efficient, sustainable',
        style: 'Small compact house',
        content: 'Very small house with essential elements',
        width: 80,
        height: 80,
        priority: 2
      },

      // COMMERCIAL PROPERTY TYPES - Food & Beverage
      {
        name: 'restaurant-fine-dining-icon',
        type: 'png',
        category: 'icon',
        subcategory: 'property-types',
        description: 'Fine dining restaurant icon',
        goal: 'Represent upscale restaurant',
        emotion: 'Elegant, sophisticated, premium',
        style: 'Upscale dining interior elements',
        content: 'Elegant table setting with wine glasses and refined elements',
        width: 80,
        height: 80,
        priority: 1
      },
      {
        name: 'cafe-icon',
        type: 'png',
        category: 'icon',
        subcategory: 'property-types',
        description: 'Cafe/coffee shop icon',
        goal: 'Represent cafe space',
        emotion: 'Cozy, casual, welcoming',
        style: 'Coffee shop interior elements',
        content: 'Coffee cup, small tables, casual seating arrangement',
        width: 80,
        height: 80,
        priority: 1
      },
      {
        name: 'bar-icon',
        type: 'png',
        category: 'icon',
        subcategory: 'property-types',
        description: 'Bar/pub icon',
        goal: 'Represent bar/pub space',
        emotion: 'Social, relaxed, evening atmosphere',
        style: 'Bar counter with seating',
        content: 'Bar counter with stools and bottles display',
        width: 80,
        height: 80,
        priority: 1
      },
      {
        name: 'fast-food-icon',
        type: 'png',
        category: 'icon',
        subcategory: 'property-types',
        description: 'Fast food restaurant icon',
        goal: 'Represent fast food establishment',
        emotion: 'Quick, casual, efficient',
        style: 'Counter service setup',
        content: 'Service counter with ordering area',
        width: 80,
        height: 80,
        priority: 1
      },

      // COMMERCIAL - Retail & Services
      {
        name: 'retail-store-icon',
        type: 'png',
        category: 'icon',
        subcategory: 'property-types',
        description: 'Retail store icon',
        goal: 'Represent retail shopping space',
        emotion: 'Shopping, commercial, organized',
        style: 'Store interior with displays',
        content: 'Store shelving and product displays',
        width: 80,
        height: 80,
        priority: 1
      },
      {
        name: 'office-corporate-icon',
        type: 'png',
        category: 'icon',
        subcategory: 'property-types',
        description: 'Corporate office icon',
        goal: 'Represent office workspace',
        emotion: 'Professional, business, productive',
        style: 'Office interior with desks',
        content: 'Office desks, chairs, and professional workspace',
        width: 80,
        height: 80,
        priority: 1
      },
      {
        name: 'gym-icon',
        type: 'png',
        category: 'icon',
        subcategory: 'property-types',
        description: 'Fitness center icon',
        goal: 'Represent fitness/gym space',
        emotion: 'Active, energetic, health-focused',
        style: 'Gym equipment representation',
        content: 'Exercise equipment and fitness area',
        width: 80,
        height: 80,
        priority: 1
      },
      {
        name: 'hotel-lobby-icon',
        type: 'png',
        category: 'icon',
        subcategory: 'property-types',
        description: 'Hotel icon',
        goal: 'Represent hotel/hospitality space',
        emotion: 'Welcoming, luxury, travel',
        style: 'Hotel lobby elements',
        content: 'Hotel reception desk and lobby seating',
        width: 80,
        height: 80,
        priority: 2
      },

      // RESIDENTIAL ROOM PHOTOS
      {
        name: 'living-room-photo',
        type: 'png',
        category: 'image',
        subcategory: 'photography',
        subsubcategory: 'residential',
        description: 'Living room example photo',
        goal: 'Show living room possibilities',
        emotion: 'Comfortable, welcoming, family-oriented',
        style: 'Professional interior photography',
        content: 'Beautiful living room with sofa, coffee table, and welcoming atmosphere',
        width: 400,
        height: 300,
        priority: 1
      },
      {
        name: 'kitchen-photo',
        type: 'png',
        category: 'image',
        subcategory: 'photography',
        subsubcategory: 'residential',
        description: 'Kitchen example photo',
        goal: 'Show kitchen design possibilities',
        emotion: 'Functional, clean, inviting',
        style: 'Professional interior photography',
        content: 'Modern kitchen with cabinets, countertops, and appliances',
        width: 400,
        height: 300,
        priority: 1
      },
      {
        name: 'bedroom-master-photo',
        type: 'png',
        category: 'image',
        subcategory: 'photography',
        subsubcategory: 'residential',
        description: 'Master bedroom example',
        goal: 'Show bedroom design possibilities',
        emotion: 'Restful, private, comfortable',
        style: 'Professional interior photography',
        content: 'Elegant master bedroom with bed, nightstands, and peaceful atmosphere',
        width: 400,
        height: 300,
        priority: 1
      },
      {
        name: 'bathroom-master-photo',
        type: 'png',
        category: 'image',
        subcategory: 'photography',
        subsubcategory: 'residential',
        description: 'Master bathroom example',
        goal: 'Show bathroom design possibilities',
        emotion: 'Clean, spa-like, luxurious',
        style: 'Professional interior photography',
        content: 'Elegant bathroom with modern fixtures and spa-like elements',
        width: 400,
        height: 300,
        priority: 1
      },
      {
        name: 'dining-room-photo',
        type: 'png',
        category: 'image',
        subcategory: 'photography',
        subsubcategory: 'residential',
        description: 'Dining room example',
        goal: 'Show dining space possibilities',
        emotion: 'Social, elegant, gathering-focused',
        style: 'Professional interior photography',
        content: 'Elegant dining room with table, chairs, and refined atmosphere',
        width: 400,
        height: 300,
        priority: 1
      },
      {
        name: 'home-office-photo',
        type: 'png',
        category: 'image',
        subcategory: 'photography',
        subsubcategory: 'residential',
        description: 'Home office example',
        goal: 'Show home workspace possibilities',
        emotion: 'Productive, organized, professional',
        style: 'Professional interior photography',
        content: 'Organized home office with desk, chair, and productive workspace',
        width: 400,
        height: 300,
        priority: 2
      },

      // COMMERCIAL SPACE PHOTOS
      {
        name: 'dining-area-restaurant-photo',
        type: 'png',
        category: 'image',
        subcategory: 'photography',
        subsubcategory: 'commercial',
        description: 'Restaurant dining area',
        goal: 'Show restaurant space design',
        emotion: 'Inviting, social, dining-focused',
        style: 'Professional commercial photography',
        content: 'Restaurant dining area with tables, chairs, and ambient lighting',
        width: 400,
        height: 300,
        priority: 1
      },
      {
        name: 'retail-floor-photo',
        type: 'png',
        category: 'image',
        subcategory: 'photography',
        subsubcategory: 'commercial',
        description: 'Retail store floor',
        goal: 'Show retail space design',
        emotion: 'Organized, shopping-focused, welcoming',
        style: 'Professional commercial photography',
        content: 'Retail store with product displays, aisles, and organized layout',
        width: 400,
        height: 300,
        priority: 1
      },
      {
        name: 'open-office-photo',
        type: 'png',
        category: 'image',
        subcategory: 'photography',
        subsubcategory: 'commercial',
        description: 'Open plan office',
        goal: 'Show office workspace design',
        emotion: 'Professional, collaborative, productive',
        style: 'Professional commercial photography',
        content: 'Open office with workstations, natural light, and collaborative spaces',
        width: 400,
        height: 300,
        priority: 1
      },

      // EXTERIOR SPACES
      {
        name: 'front-yard-photo',
        type: 'png',
        category: 'image',
        subcategory: 'photography',
        subsubcategory: 'exterior',
        description: 'Front yard/garden',
        goal: 'Show front yard possibilities',
        emotion: 'Welcoming, curb appeal, natural',
        style: 'Professional exterior photography',
        content: 'Beautiful front yard with landscaping, walkway, and welcoming entrance',
        width: 400,
        height: 300,
        priority: 1
      },
      {
        name: 'backyard-photo',
        type: 'png',
        category: 'image',
        subcategory: 'photography',
        subsubcategory: 'exterior',
        description: 'Backyard space',
        goal: 'Show backyard possibilities',
        emotion: 'Private, recreational, outdoor living',
        style: 'Professional exterior photography',
        content: 'Beautiful backyard with seating area, plants, and outdoor living elements',
        width: 400,
        height: 300,
        priority: 1
      },
      {
        name: 'patio-photo',
        type: 'png',
        category: 'image',
        subcategory: 'photography',
        subsubcategory: 'exterior',
        description: 'Patio/deck area',
        goal: 'Show outdoor entertaining space',
        emotion: 'Relaxing, entertaining, outdoor comfort',
        style: 'Professional exterior photography',
        content: 'Beautiful patio with outdoor furniture, plants, and comfortable seating',
        width: 400,
        height: 300,
        priority: 1
      },

      // FUNCTION CATEGORY ICONS
      {
        name: 'relaxation-function-icon',
        type: 'png',
        category: 'icon',
        subcategory: 'functions',
        description: 'Relaxation/rest function',
        goal: 'Represent relaxation purpose',
        emotion: 'Calm, peaceful, restful',
        style: 'Simple, clear iconography',
        content: 'Relaxation symbol like reclining chair or zen elements',
        width: 64,
        height: 64,
        priority: 1
      },
      {
        name: 'work-function-icon',
        type: 'png',
        category: 'icon',
        subcategory: 'functions',
        description: 'Work/productivity function',
        goal: 'Represent work purpose',
        emotion: 'Productive, focused, professional',
        style: 'Simple, clear iconography',
        content: 'Work symbol like desk, laptop, or productivity elements',
        width: 64,
        height: 64,
        priority: 1
      },
      {
        name: 'dining-function-icon',
        type: 'png',
        category: 'icon',
        subcategory: 'functions',
        description: 'Dining/eating function',
        goal: 'Represent dining purpose',
        emotion: 'Social, nourishing, gathering',
        style: 'Simple, clear iconography',
        content: 'Dining symbol like table setting, utensils, or dining elements',
        width: 64,
        height: 64,
        priority: 1
      },
      {
        name: 'sleeping-function-icon',
        type: 'png',
        category: 'icon',
        subcategory: 'functions',
        description: 'Sleep/rest function',
        goal: 'Represent sleeping purpose',
        emotion: 'Peaceful, restful, private',
        style: 'Simple, clear iconography',
        content: 'Sleep symbol like bed, moon, or rest elements',
        width: 64,
        height: 64,
        priority: 1
      },
      {
        name: 'cooking-function-icon',
        type: 'png',
        category: 'icon',
        subcategory: 'functions',
        description: 'Cooking/food prep function',
        goal: 'Represent cooking purpose',
        emotion: 'Creative, nourishing, functional',
        style: 'Simple, clear iconography',
        content: 'Cooking symbol like chef hat, stove, or cooking utensils',
        width: 64,
        height: 64,
        priority: 1
      },
      {
        name: 'entertainment-function-icon',
        type: 'png',
        category: 'icon',
        subcategory: 'functions',
        description: 'Entertainment function',
        goal: 'Represent entertainment purpose',
        emotion: 'Fun, social, engaging',
        style: 'Simple, clear iconography',
        content: 'Entertainment symbol like TV, game controller, or fun elements',
        width: 64,
        height: 64,
        priority: 1
      },
      {
        name: 'storage-function-icon',
        type: 'png',
        category: 'icon',
        subcategory: 'functions',
        description: 'Storage/organization function',
        goal: 'Represent storage purpose',
        emotion: 'Organized, efficient, tidy',
        style: 'Simple, clear iconography',
        content: 'Storage symbol like shelves, boxes, or organization elements',
        width: 64,
        height: 64,
        priority: 1
      },

      // FURNITURE CATEGORY ICONS
      {
        name: 'seating-category-icon',
        type: 'png',
        category: 'icon',
        subcategory: 'furniture',
        description: 'Seating furniture category',
        goal: 'Represent all seating types',
        emotion: 'Comfort, social, relaxation',
        style: 'Furniture category representation',
        content: 'Chair or sofa silhouette representing seating furniture',
        width: 80,
        height: 80,
        priority: 1
      },
      {
        name: 'tables-category-icon',
        type: 'png',
        category: 'icon',
        subcategory: 'furniture',
        description: 'Tables furniture category',
        goal: 'Represent all table types',
        emotion: 'Functional, gathering, support',
        style: 'Furniture category representation',
        content: 'Table silhouette representing table furniture',
        width: 80,
        height: 80,
        priority: 1
      },
      {
        name: 'storage-category-icon',
        type: 'png',
        category: 'icon',
        subcategory: 'furniture',
        description: 'Storage furniture category',
        goal: 'Represent storage furniture',
        emotion: 'Organization, efficiency, tidiness',
        style: 'Furniture category representation',
        content: 'Cabinet or shelf silhouette representing storage furniture',
        width: 80,
        height: 80,
        priority: 1
      },
      {
        name: 'lighting-category-icon',
        type: 'png',
        category: 'icon',
        subcategory: 'furniture',
        description: 'Lighting fixtures category',
        goal: 'Represent lighting options',
        emotion: 'Ambiance, warmth, illumination',
        style: 'Furniture category representation',
        content: 'Lamp or light fixture representing lighting',
        width: 80,
        height: 80,
        priority: 1
      },
      {
        name: 'beds-category-icon',
        type: 'png',
        category: 'icon',
        subcategory: 'furniture',
        description: 'Beds and bedroom furniture',
        goal: 'Represent bedroom furniture',
        emotion: 'Rest, comfort, privacy',
        style: 'Furniture category representation',
        content: 'Bed silhouette representing bedroom furniture',
        width: 80,
        height: 80,
        priority: 1
      },

      // SPECIFIC FURNITURE ITEMS
      {
        name: 'sofa-modern-photo',
        type: 'png',
        category: 'image',
        subcategory: 'photography',
        subsubcategory: 'furniture',
        description: 'Modern sofa photo',
        goal: 'Show modern sofa option',
        emotion: 'Contemporary, sleek, comfortable',
        style: 'Product photography',
        content: 'Modern sofa with clean lines and contemporary design',
        width: 300,
        height: 200,
        priority: 1
      },
      {
        name: 'chair-dining-photo',
        type: 'png',
        category: 'image',
        subcategory: 'photography',
        subsubcategory: 'furniture',
        description: 'Dining chair photo',
        goal: 'Show dining chair option',
        emotion: 'Functional, stylish, comfortable',
        style: 'Product photography',
        content: 'Elegant dining chair with good proportions',
        width: 300,
        height: 200,
        priority: 1
      },
      {
        name: 'table-coffee-photo',
        type: 'png',
        category: 'image',
        subcategory: 'photography',
        subsubcategory: 'furniture',
        description: 'Coffee table photo',
        goal: 'Show coffee table option',
        emotion: 'Central, functional, stylish',
        style: 'Product photography',
        content: 'Coffee table with attractive design and proportions',
        width: 300,
        height: 200,
        priority: 1
      },

      // TEXTURE & MATERIAL ICONS
      {
        name: 'wood-texture-icon',
        type: 'png',
        category: 'icon',
        subcategory: 'materials',
        description: 'Wood materials icon',
        goal: 'Represent wood material category',
        emotion: 'Natural, warm, organic',
        style: 'Material representation',
        content: 'Wood grain pattern or wood plank representation',
        width: 64,
        height: 64,
        priority: 2
      },
      {
        name: 'metal-texture-icon',
        type: 'png',
        category: 'icon',
        subcategory: 'materials',
        description: 'Metal materials icon',
        goal: 'Represent metal material category',
        emotion: 'Modern, industrial, sleek',
        style: 'Material representation',
        content: 'Metal surface or metallic finish representation',
        width: 64,
        height: 64,
        priority: 2
      },
      {
        name: 'fabric-texture-icon',
        type: 'png',
        category: 'icon',
        subcategory: 'materials',
        description: 'Fabric/textile materials icon',
        goal: 'Represent fabric material category',
        emotion: 'Soft, comfortable, cozy',
        style: 'Material representation',
        content: 'Fabric weave pattern or textile representation',
        width: 64,
        height: 64,
        priority: 2
      },
      {
        name: 'stone-texture-icon',
        type: 'png',
        category: 'icon',
        subcategory: 'materials',
        description: 'Stone/marble materials icon',
        goal: 'Represent stone material category',
        emotion: 'Luxurious, natural, durable',
        style: 'Material representation',
        content: 'Stone or marble pattern representation',
        width: 64,
        height: 64,
        priority: 2
      },

      // TEXTURE SAMPLES
      {
        name: 'wood-oak-sample',
        type: 'png',
        category: 'image',
        subcategory: 'photography',
        subsubcategory: 'textures',
        description: 'Oak wood texture sample',
        goal: 'Show oak wood texture',
        emotion: 'Natural, warm, traditional',
        style: 'High-resolution texture close-up',
        content: 'Close-up oak wood grain texture showing natural patterns',
        width: 200,
        height: 200,
        priority: 2
      },
      {
        name: 'fabric-linen-sample',
        type: 'png',
        category: 'image',
        subcategory: 'photography',
        subsubcategory: 'textures',
        description: 'Linen fabric texture sample',
        goal: 'Show linen fabric texture',
        emotion: 'Natural, relaxed, breathable',
        style: 'High-resolution texture close-up',
        content: 'Close-up linen fabric weave showing natural fiber texture',
        width: 200,
        height: 200,
        priority: 2
      },

      // COLOR PALETTE ICONS
      {
        name: 'neutral-palette-icon',
        type: 'png',
        category: 'icon',
        subcategory: 'colors',
        description: 'Neutral colors palette icon',
        goal: 'Represent neutral color schemes',
        emotion: 'Calm, versatile, timeless',
        style: 'Color swatch arrangement',
        content: 'Neutral color swatches in beige, white, gray arrangement',
        width: 80,
        height: 80,
        priority: 1
      },
      {
        name: 'warm-palette-icon',
        type: 'png',
        category: 'icon',
        subcategory: 'colors',
        description: 'Warm colors palette icon',
        goal: 'Represent warm color schemes',
        emotion: 'Cozy, inviting, energetic',
        style: 'Color swatch arrangement',
        content: 'Warm color swatches in reds, oranges, yellows arrangement',
        width: 80,
        height: 80,
        priority: 1
      },
      {
        name: 'cool-palette-icon',
        type: 'png',
        category: 'icon',
        subcategory: 'colors',
        description: 'Cool colors palette icon',
        goal: 'Represent cool color schemes',
        emotion: 'Calm, refreshing, serene',
        style: 'Color swatch arrangement',
        content: 'Cool color swatches in blues, greens, purples arrangement',
        width: 80,
        height: 80,
        priority: 1
      },

      // SPECIFIC COLOR PALETTES
      {
        name: 'palette-modern-minimalist',
        type: 'png',
        category: 'image',
        subcategory: 'palette',
        description: 'Modern minimalist color palette',
        goal: 'Show minimalist color scheme',
        emotion: 'Clean, simple, sophisticated',
        style: '5-6 color swatches per palette',
        content: 'White, light gray, charcoal, and beige color swatches arranged horizontally',
        width: 300,
        height: 100,
        priority: 1
      },
      {
        name: 'palette-warm-cozy',
        type: 'png',
        category: 'image',
        subcategory: 'palette',
        description: 'Warm cozy color palette',
        goal: 'Show warm cozy color scheme',
        emotion: 'Warm, comfortable, inviting',
        style: '5-6 color swatches per palette',
        content: 'Beige, brown, cream, and warm earth tone color swatches arranged horizontally',
        width: 300,
        height: 100,
        priority: 1
      },

      // DESIGN STYLE ICONS
      {
        name: 'style-modern-icon',
        type: 'png',
        category: 'icon',
        subcategory: 'styles',
        description: 'Modern style icon',
        goal: 'Represent modern design style',
        emotion: 'Contemporary, clean, sophisticated',
        style: 'Design style representation',
        content: 'Clean geometric shapes representing modern design aesthetics',
        width: 80,
        height: 80,
        priority: 1
      },
      {
        name: 'style-traditional-icon',
        type: 'png',
        category: 'icon',
        subcategory: 'styles',
        description: 'Traditional style icon',
        goal: 'Represent traditional design style',
        emotion: 'Classic, elegant, timeless',
        style: 'Design style representation',
        content: 'Classical elements representing traditional design aesthetics',
        width: 80,
        height: 80,
        priority: 1
      },
      {
        name: 'style-minimalist-icon',
        type: 'png',
        category: 'icon',
        subcategory: 'styles',
        description: 'Minimalist style icon',
        goal: 'Represent minimalist design style',
        emotion: 'Simple, clean, uncluttered',
        style: 'Design style representation',
        content: 'Simple minimal shapes representing minimalist design aesthetics',
        width: 80,
        height: 80,
        priority: 1
      },
      {
        name: 'style-industrial-icon',
        type: 'png',
        category: 'icon',
        subcategory: 'styles',
        description: 'Industrial style icon',
        goal: 'Represent industrial design style',
        emotion: 'Raw, urban, authentic',
        style: 'Design style representation',
        content: 'Industrial elements like exposed brick or metal representing industrial style',
        width: 80,
        height: 80,
        priority: 1
      },

      // STYLE REFERENCE PHOTOS
      {
        name: 'modern-style-reference',
        type: 'png',
        category: 'image',
        subcategory: 'photography',
        subsubcategory: 'styles',
        description: 'Modern room style reference',
        goal: 'Show modern design style in practice',
        emotion: 'Contemporary, clean, sophisticated',
        style: 'Professional interior photography',
        content: 'Modern interior with clean lines, minimal furniture, neutral colors',
        width: 400,
        height: 300,
        priority: 1
      },
      {
        name: 'traditional-style-reference',
        type: 'png',
        category: 'image',
        subcategory: 'photography',
        subsubcategory: 'styles',
        description: 'Traditional room style reference',
        goal: 'Show traditional design style in practice',
        emotion: 'Classic, elegant, timeless',
        style: 'Professional interior photography',
        content: 'Traditional interior with classic furniture, rich fabrics, warm colors',
        width: 400,
        height: 300,
        priority: 1
      },

      // UI NAVIGATION ICONS
      {
        name: 'camera-capture-3d-icon',
        type: 'png',
        category: 'icon',
        subcategory: 'navigation',
        description: 'Camera for photo capture',
        goal: 'Represent photo capture action',
        emotion: 'Action-oriented, capture, create',
        style: 'Modern 3D style matching brand',
        content: 'Modern camera icon with lens details',
        width: 48,
        height: 48,
        priority: 1
      },
      {
        name: 'ai-processing-icon',
        type: 'png',
        category: 'icon',
        subcategory: 'navigation',
        description: 'AI processing indicator',
        goal: 'Represent AI processing',
        emotion: 'Intelligent, processing, modern',
        style: 'Modern 3D style matching brand',
        content: 'AI brain or neural network representation',
        width: 48,
        height: 48,
        priority: 1
      },
      {
        name: 'next-step-icon',
        type: 'png',
        category: 'icon',
        subcategory: 'navigation',
        description: 'Continue/next action',
        goal: 'Represent forward progression',
        emotion: 'Progress, forward, continue',
        style: 'Modern 3D style matching brand',
        content: 'Forward arrow or next indicator',
        width: 48,
        height: 48,
        priority: 1
      },

      // EMPTY STATE ILLUSTRATIONS
      {
        name: 'empty-projects-illustration',
        type: 'png',
        category: 'image',
        subcategory: 'illustration',
        subsubcategory: 'empty-states',
        description: 'No projects yet illustration',
        goal: 'Make empty project state encouraging',
        emotion: 'Encouraging, potential, possibility',
        style: 'Friendly, professional illustration',
        content: 'Empty folder or workspace with creative potential elements',
        width: 200,
        height: 150,
        priority: 2
      },
      {
        name: 'loading-ai-illustration',
        type: 'png',
        category: 'image',
        subcategory: 'illustration',
        subsubcategory: 'features',
        description: 'AI processing illustration',
        goal: 'Show AI processing state',
        emotion: 'Intelligence, processing, progress',
        style: 'Friendly, professional illustration',
        content: 'AI processing visualization with modern elements',
        width: 200,
        height: 150,
        priority: 2
      },

      // ============ INDIVIDUAL STYLE REFERENCES (NO TEXT) ============
      {
        name: 'scandinavian-style-individual',
        type: 'png',
        category: 'reference',
        subcategory: 'styles',
        description: 'Scandinavian style room',
        goal: 'Show clean scandinavian design',
        emotion: 'Clean, bright, cozy',
        style: 'Light woods, whites, hygge elements',
        content: 'Living room with light wood, white walls, cozy textiles',
        width: 400,
        height: 300,
        priority: 2
      },
      {
        name: 'industrial-style-individual',
        type: 'png',
        category: 'reference',
        subcategory: 'styles', 
        description: 'Industrial style room',
        goal: 'Show industrial design elements',
        emotion: 'Raw, urban, edgy',
        style: 'Exposed brick, metal, concrete',
        content: 'Room with exposed brick walls, metal fixtures, concrete floors',
        width: 400,
        height: 300,
        priority: 2
      },
      {
        name: 'bohemian-style-individual',
        type: 'png',
        category: 'reference',
        subcategory: 'styles',
        description: 'Bohemian style room',
        goal: 'Show eclectic bohemian style',
        emotion: 'Free-spirited, artistic, layered',
        style: 'Mixed patterns, plants, textiles',
        content: 'Room with colorful textiles, plants, mixed furniture',
        width: 400,
        height: 300,
        priority: 2
      },
      {
        name: 'contemporary-style-individual',
        type: 'png',
        category: 'reference',
        subcategory: 'styles',
        description: 'Contemporary style room', 
        goal: 'Show current contemporary design',
        emotion: 'Current, sophisticated, clean',
        style: 'Current trends, mixed materials',
        content: 'Modern room with current design trends and materials',
        width: 400,
        height: 300,
        priority: 2
      },
      {
        name: 'midcentury-style-individual',
        type: 'png',
        category: 'reference',
        subcategory: 'styles',
        description: 'Mid-century modern style room',
        goal: 'Show mid-century design elements',
        emotion: 'Retro, sophisticated, timeless',
        style: '1950s-60s furniture, clean lines',
        content: 'Room with mid-century furniture, teak wood, clean lines',
        width: 400,
        height: 300,
        priority: 2
      },
      {
        name: 'rustic-style-individual',
        type: 'png',
        category: 'reference',
        subcategory: 'styles',
        description: 'Rustic style room',
        goal: 'Show rustic design elements',
        emotion: 'Natural, cozy, warm',
        style: 'Natural materials, wood, stone',
        content: 'Room with natural wood, stone elements, cozy atmosphere',
        width: 400,
        height: 300,
        priority: 2
      },
      {
        name: 'transitional-style-individual',
        type: 'png',
        category: 'reference',
        subcategory: 'styles',
        description: 'Transitional style room',
        goal: 'Show transitional design blend',
        emotion: 'Balanced, comfortable, timeless',
        style: 'Traditional and contemporary mix',
        content: 'Room blending traditional and modern elements',
        width: 400,
        height: 300,
        priority: 2
      },

      // ============ INDIVIDUAL TEXTURE SAMPLES (NO TEXT) ============
      {
        name: 'wood-walnut-sample',
        type: 'png',
        category: 'texture',
        subcategory: 'wood',
        description: 'Walnut wood texture',
        goal: 'Show walnut wood grain',
        emotion: 'Rich, luxurious, warm',
        style: 'Natural wood grain pattern',
        content: 'Close-up of walnut wood grain texture',
        width: 200,
        height: 200,
        priority: 2
      },
      {
        name: 'wood-pine-sample',
        type: 'png',
        category: 'texture',
        subcategory: 'wood',
        description: 'Pine wood texture',
        goal: 'Show pine wood characteristics',
        emotion: 'Natural, light, fresh',
        style: 'Light wood grain',
        content: 'Close-up of pine wood grain texture',
        width: 200,
        height: 200,
        priority: 2
      },
      {
        name: 'metal-brass-sample',
        type: 'png',
        category: 'texture',
        subcategory: 'metal',
        description: 'Brass metal texture',
        goal: 'Show brass finish',
        emotion: 'Warm, elegant, classic',
        style: 'Polished brass surface',
        content: 'Close-up of polished brass metal surface',
        width: 200,
        height: 200,
        priority: 2
      },
      {
        name: 'metal-steel-sample',
        type: 'png',
        category: 'texture',
        subcategory: 'metal',
        description: 'Steel metal texture',
        goal: 'Show steel finish',
        emotion: 'Modern, industrial, cool',
        style: 'Brushed steel surface',
        content: 'Close-up of brushed steel metal surface',
        width: 200,
        height: 200,
        priority: 2
      },
      {
        name: 'fabric-cotton-sample',
        type: 'png',
        category: 'texture',
        subcategory: 'fabric',
        description: 'Cotton fabric texture',
        goal: 'Show cotton weave',
        emotion: 'Soft, comfortable, natural',
        style: 'Natural cotton weave',
        content: 'Close-up of cotton fabric weave pattern',
        width: 200,
        height: 200,
        priority: 2
      },
      {
        name: 'fabric-velvet-sample',
        type: 'png',
        category: 'texture',
        subcategory: 'fabric',
        description: 'Velvet fabric texture',
        goal: 'Show velvet texture',
        emotion: 'Luxurious, soft, rich',
        style: 'Rich velvet surface',
        content: 'Close-up of velvet fabric texture',
        width: 200,
        height: 200,
        priority: 2
      },
      {
        name: 'stone-marble-sample',
        type: 'png',
        category: 'texture',
        subcategory: 'stone',
        description: 'Marble stone texture',
        goal: 'Show marble veining',
        emotion: 'Elegant, luxurious, timeless',
        style: 'Natural marble pattern',
        content: 'Close-up of marble stone with natural veining',
        width: 200,
        height: 200,
        priority: 2
      },
      {
        name: 'stone-granite-sample',
        type: 'png',
        category: 'texture',
        subcategory: 'stone',
        description: 'Granite stone texture',
        goal: 'Show granite speckled pattern',
        emotion: 'Durable, natural, sophisticated',
        style: 'Speckled granite surface',
        content: 'Close-up of granite stone with speckled pattern',
        width: 200,
        height: 200,
        priority: 2
      },

      // ============ ADDITIONAL PRIORITY 2 ASSETS ============
      
      // ADDITIONAL ROOM TYPES
      {
        name: 'garage-photo',
        type: 'png',
        category: 'photography',
        subcategory: 'residential',
        description: 'Garage space example',
        goal: 'Show garage organization and design',
        emotion: 'Organized, functional, clean',
        style: 'Well-organized garage space',
        content: 'Garage with storage solutions and clean organization',
        width: 400,
        height: 300,
        priority: 2
      },
      {
        name: 'basement-photo',
        type: 'png',
        category: 'photography',
        subcategory: 'residential',
        description: 'Basement space example',
        goal: 'Show basement potential',
        emotion: 'Cozy, finished, livable',
        style: 'Finished basement space',
        content: 'Well-finished basement with seating and lighting',
        width: 400,
        height: 300,
        priority: 2
      },
      {
        name: 'attic-photo',
        type: 'png',
        category: 'photography',
        subcategory: 'residential',
        description: 'Attic space example',
        goal: 'Show attic conversion potential',
        emotion: 'Bright, converted, useful',
        style: 'Converted attic space',
        content: 'Converted attic with sloped ceilings and natural light',
        width: 400,
        height: 300,
        priority: 2
      },
      {
        name: 'balcony-photo',
        type: 'png',
        category: 'photography',
        subcategory: 'residential',
        description: 'Balcony space example',
        goal: 'Show balcony design',
        emotion: 'Fresh, outdoor, relaxing',
        style: 'Decorated balcony space',
        content: 'Balcony with plants, seating, and outdoor elements',
        width: 400,
        height: 300,
        priority: 2
      },

      // ADDITIONAL COMMERCIAL SPACES
      {
        name: 'spa-icon',
        type: 'png',
        category: 'icon',
        subcategory: 'property-types',
        description: 'Spa/wellness center icon',
        goal: 'Represent wellness space',
        emotion: 'Calm, relaxing, zen',
        style: 'Peaceful spa elements',
        content: 'Spa-related symbols like lotus or zen stones',
        width: 80,
        height: 80,
        priority: 2
      },
      {
        name: 'clinic-icon',
        type: 'png',
        category: 'icon',
        subcategory: 'property-types',
        description: 'Medical clinic icon',
        goal: 'Represent medical space',
        emotion: 'Clean, professional, safe',
        style: 'Medical facility representation',
        content: 'Clean medical facility with cross symbol',
        width: 80,
        height: 80,
        priority: 2
      },
      {
        name: 'salon-icon',
        type: 'png',
        category: 'icon',
        subcategory: 'property-types',
        description: 'Hair salon icon',
        goal: 'Represent salon business',
        emotion: 'Stylish, modern, trendy',
        style: 'Hair salon elements',
        content: 'Salon chair or styling elements',
        width: 80,
        height: 80,
        priority: 2
      },

      // ADDITIONAL COMMERCIAL PHOTOGRAPHY
      {
        name: 'spa-treatment-room-photo',
        type: 'png',
        category: 'photography',
        subcategory: 'commercial',
        description: 'Spa treatment room',
        goal: 'Show relaxing treatment space',
        emotion: 'Calm, serene, therapeutic',
        style: 'Clean spa interior',
        content: 'Spa treatment room with massage table and calming elements',
        width: 400,
        height: 300,
        priority: 2
      },
      {
        name: 'clinic-waiting-room-photo',
        type: 'png',
        category: 'photography',
        subcategory: 'commercial',
        description: 'Medical clinic waiting room',
        goal: 'Show professional medical space',
        emotion: 'Clean, professional, comfortable',
        style: 'Modern medical facility',
        content: 'Clean waiting room with comfortable seating',
        width: 400,
        height: 300,
        priority: 2
      },
      {
        name: 'salon-interior-photo',
        type: 'png',
        category: 'photography',
        subcategory: 'commercial',
        description: 'Hair salon interior',
        goal: 'Show stylish salon space',
        emotion: 'Trendy, modern, stylish',
        style: 'Contemporary salon design',
        content: 'Modern salon with styling stations and mirrors',
        width: 400,
        height: 300,
        priority: 2
      },

      // ADDITIONAL FURNITURE ITEMS
      {
        name: 'armchair-accent-photo',
        type: 'png',
        category: 'photography',
        subcategory: 'furniture',
        description: 'Accent armchair photo',
        goal: 'Show individual accent chair',
        emotion: 'Comfortable, stylish, focal',
        style: 'Statement accent chair',
        content: 'Single accent armchair with distinctive design',
        width: 300,
        height: 200,
        priority: 2
      },
      {
        name: 'bookshelf-unit-photo',
        type: 'png',
        category: 'photography',
        subcategory: 'furniture',
        description: 'Bookshelf unit photo',
        goal: 'Show storage and display',
        emotion: 'Organized, intellectual, display',
        style: 'Modern bookshelf design',
        content: 'Bookshelf unit with books and decorative items',
        width: 300,
        height: 200,
        priority: 2
      },
      {
        name: 'desk-work-photo',
        type: 'png',
        category: 'photography',
        subcategory: 'furniture',
        description: 'Work desk photo',
        goal: 'Show workspace furniture',
        emotion: 'Productive, organized, functional',
        style: 'Modern work desk',
        content: 'Clean work desk with minimal setup',
        width: 300,
        height: 200,
        priority: 2
      },
      {
        name: 'ottoman-storage-photo',
        type: 'png',
        category: 'photography',
        subcategory: 'furniture',
        description: 'Storage ottoman photo',
        goal: 'Show dual-purpose furniture',
        emotion: 'Practical, comfortable, versatile',
        style: 'Functional ottoman design',
        content: 'Storage ottoman that serves as seat and storage',
        width: 300,
        height: 200,
        priority: 2
      },

      // ADDITIONAL COLOR PALETTES
      {
        name: 'palette-earth-tones',
        type: 'png',
        category: 'color-palette',
        subcategory: 'themed',
        description: 'Earth tones color palette',
        goal: 'Show natural color scheme',
        emotion: 'Natural, grounding, organic',
        style: 'Earth-inspired colors',
        content: 'Color swatches in browns, tans, warm beiges',
        width: 300,
        height: 100,
        priority: 2
      },
      {
        name: 'palette-ocean-blues',
        type: 'png',
        category: 'color-palette',
        subcategory: 'themed',
        description: 'Ocean blues color palette',
        goal: 'Show calming blue scheme',
        emotion: 'Calm, refreshing, peaceful',
        style: 'Ocean-inspired blues',
        content: 'Color swatches in various blue tones',
        width: 300,
        height: 100,
        priority: 2
      },
      {
        name: 'palette-sunset-warm',
        type: 'png',
        category: 'color-palette',
        subcategory: 'themed',
        description: 'Sunset warm color palette',
        goal: 'Show warm evening colors',
        emotion: 'Warm, cozy, romantic',
        style: 'Sunset-inspired warm tones',
        content: 'Color swatches in oranges, pinks, warm yellows',
        width: 300,
        height: 100,
        priority: 2
      },

      // ADDITIONAL FUNCTION ICONS
      {
        name: 'cleaning-function-icon',
        type: 'png',
        category: 'icon',
        subcategory: 'functions',
        description: 'Cleaning/laundry function',
        goal: 'Represent cleaning activities',
        emotion: 'Clean, organized, fresh',
        style: 'Cleaning-related symbols',
        content: 'Cleaning supplies or laundry symbols',
        width: 64,
        height: 64,
        priority: 2
      },
      {
        name: 'exercise-function-icon',
        type: 'png',
        category: 'icon',
        subcategory: 'functions',
        description: 'Exercise/fitness function',
        goal: 'Represent fitness activities',
        emotion: 'Active, healthy, energetic',
        style: 'Fitness-related symbols',
        content: 'Exercise equipment or fitness symbols',
        width: 64,
        height: 64,
        priority: 2
      },
      {
        name: 'reading-function-icon',
        type: 'png',
        category: 'icon',
        subcategory: 'functions',
        description: 'Reading/study function',
        goal: 'Represent reading and study',
        emotion: 'Peaceful, intellectual, focused',
        style: 'Reading-related symbols',
        content: 'Book or reading-related symbols',
        width: 64,
        height: 64,
        priority: 2
      },

      // ============ PRIORITY 3 ASSETS ============
      
      // DETAILED STYLE VARIATIONS
      {
        name: 'modern-luxury-style-reference',
        type: 'png',
        category: 'reference',
        subcategory: 'styles',
        description: 'Modern luxury style room',
        goal: 'Show high-end modern design',
        emotion: 'Luxurious, sophisticated, expensive',
        style: 'Premium modern elements',
        content: 'Luxury modern room with premium materials',
        width: 400,
        height: 300,
        priority: 3
      },
      {
        name: 'farmhouse-style-reference',
        type: 'png',
        category: 'reference',
        subcategory: 'styles',
        description: 'Farmhouse style room',
        goal: 'Show farmhouse design elements',
        emotion: 'Rustic, cozy, homey',
        style: 'Country farmhouse elements',
        content: 'Farmhouse style room with wooden beams and vintage elements',
        width: 400,
        height: 300,
        priority: 3
      },
      {
        name: 'art-deco-style-reference',
        type: 'png',
        category: 'reference',
        subcategory: 'styles',
        description: 'Art Deco style room',
        goal: 'Show art deco design',
        emotion: 'Glamorous, geometric, vintage',
        style: 'Art deco patterns and materials',
        content: 'Art deco room with geometric patterns and metallic accents',
        width: 400,
        height: 300,
        priority: 3
      },

      // DETAILED TEXTURE VARIATIONS
      {
        name: 'leather-brown-sample',
        type: 'png',
        category: 'texture',
        subcategory: 'leather',
        description: 'Brown leather texture',
        goal: 'Show leather material quality',
        emotion: 'Rich, luxurious, classic',
        style: 'Natural leather surface',
        content: 'Close-up of brown leather texture',
        width: 200,
        height: 200,
        priority: 3
      },
      {
        name: 'ceramic-tile-sample',
        type: 'png',
        category: 'texture',
        subcategory: 'ceramic',
        description: 'Ceramic tile texture',
        goal: 'Show ceramic surface',
        emotion: 'Clean, durable, modern',
        style: 'Smooth ceramic finish',
        content: 'Close-up of ceramic tile surface',
        width: 200,
        height: 200,
        priority: 3
      },
      {
        name: 'glass-frosted-sample',
        type: 'png',
        category: 'texture',
        subcategory: 'glass',
        description: 'Frosted glass texture',
        goal: 'Show glass treatment',
        emotion: 'Light, privacy, modern',
        style: 'Translucent glass surface',
        content: 'Close-up of frosted glass texture',
        width: 200,
        height: 200,
        priority: 3
      },

      // UI ENHANCEMENT ASSETS
      {
        name: 'save-favorite-icon',
        type: 'png',
        category: 'icon',
        subcategory: 'navigation',
        description: 'Save/favorite action',
        goal: 'Save design elements',
        emotion: 'Helpful, organization, keep',
        style: 'Heart or star symbol',
        content: 'Save/favorite icon for user interactions',
        width: 48,
        height: 48,
        priority: 3
      },
      {
        name: 'share-design-icon',
        type: 'png',
        category: 'icon',
        subcategory: 'navigation',
        description: 'Share design',
        goal: 'Share completed designs',
        emotion: 'Social, sharing, connectivity',
        style: 'Share symbol',
        content: 'Share icon for design sharing',
        width: 48,
        height: 48,
        priority: 3
      },
      {
        name: 'edit-selection-icon',
        type: 'png',
        category: 'icon',
        subcategory: 'navigation',
        description: 'Edit/modify',
        goal: 'Edit design selections',
        emotion: 'Control, customization, refinement',
        style: 'Edit/pencil symbol',
        content: 'Edit icon for modification actions',
        width: 48,
        height: 48,
        priority: 3
      },

      // EMPTY STATE ILLUSTRATIONS
      {
        name: 'empty-favorites-illustration',
        type: 'png',
        category: 'illustration',
        subcategory: 'empty-states',
        description: 'No favorites yet illustration',
        goal: 'Show empty favorites state',
        emotion: 'Encouraging, potential, hopeful',
        style: 'Friendly, encouraging illustration',
        content: 'Illustration showing empty favorites with encouraging message',
        width: 200,
        height: 150,
        priority: 3
      },
      {
        name: 'empty-search-illustration',
        type: 'png',
        category: 'illustration',
        subcategory: 'empty-states',
        description: 'No search results illustration',
        goal: 'Show no search results',
        emotion: 'Helpful, suggestive, guiding',
        style: 'Search-related illustration',
        content: 'Illustration for when no search results are found',
        width: 200,
        height: 150,
        priority: 3
      },
      {
        name: 'success-completion-illustration',
        type: 'png',
        category: 'illustration',
        subcategory: 'features',
        description: 'Task completed illustration',
        goal: 'Show successful completion',
        emotion: 'Success, achievement, satisfaction',
        style: 'Celebratory, positive illustration',
        content: 'Success illustration with checkmark or celebration elements',
        width: 200,
        height: 150,
        priority: 3
      }

      // This represents the complete 500+ asset system with NO TEXT
      // All categories from COMPREHENSIVE-ASSET-REQUIREMENTS.md included
    ];
  }

  /**
   * Generate assets by priority level
   */
  async generateByPriority(targetPriority = 1, limit = null) {
    console.log(`🎯 Starting Priority ${targetPriority} Assets Generation (NO TEXT)...`);
    console.log('═'.repeat(60));
    
    const allSpecs = this.getAllAssetSpecs();
    let prioritySpecs = allSpecs.filter(spec => spec.priority === targetPriority);
    
    if (limit) {
      prioritySpecs = prioritySpecs.slice(0, limit);
    }
    
    console.log(`📊 Priority ${targetPriority} assets to generate: ${prioritySpecs.length}`);
    console.log(`⚠️  CRITICAL: All images will be generated WITHOUT TEXT`);
    
    if (prioritySpecs.length === 0) {
      console.log(`⚠️  No Priority ${targetPriority} assets found!`);
      return { completed: 0, failed: 0, total: 0 };
    }
    
    let completed = 0;
    let failed = 0;

    for (const spec of prioritySpecs) {
      const progress = `(${completed + failed + 1}/${prioritySpecs.length})`;
      console.log(`\\n🎯 Generating P${targetPriority} (NO TEXT): ${spec.name} ${progress}`);
      
      try {
        const success = await this.generateAsset(spec);
        if (success) {
          completed++;
        } else {
          failed++;
        }
      } catch (error) {
        failed++;
        console.error(`💥 Error generating ${spec.name}:`, error.message);
      }
      
      // Rate limiting delay
      await new Promise(resolve => setTimeout(resolve, 2000));
    }
    
    console.log(`\\n✅ Priority ${targetPriority} complete! ${completed}/${prioritySpecs.length} assets generated (NO TEXT)`);
    return { completed, failed, total: prioritySpecs.length };
  }

  /**
   * Generate all assets sequentially
   */
  async generateAllAssets() {
    console.log('🚀 Starting Expanded Asset Generation (NO TEXT)...');
    console.log('All 500+ assets from COMPREHENSIVE-ASSET-REQUIREMENTS.md');
    console.log('⚠️  CRITICAL: NO TEXT will appear on any generated images');
    console.log('═'.repeat(60));
    
    const startTime = Date.now();
    
    try {
      // Generate Priority 1 assets first
      console.log('\\n🎯 Phase 1: Priority 1 (Essential) Assets (NO TEXT)...');
      const p1Results = await this.generateByPriority(1);
      
      console.log('\\n📊 Phase 2: Priority 2 (Important) Assets (NO TEXT)...');
      const p2Results = await this.generateByPriority(2);
      
      console.log('\\n🎨 Phase 3: Priority 3 (Nice-to-have) Assets (NO TEXT)...');
      const p3Results = await this.generateByPriority(3);
      
      const totalTime = Date.now() - startTime;
      const totalCompleted = p1Results.completed + p2Results.completed + p3Results.completed;
      const totalFailed = p1Results.failed + p2Results.failed + p3Results.failed;
      const totalAssets = p1Results.total + p2Results.total + p3Results.total;
      
      console.log('\\n' + '═'.repeat(60));
      console.log('🎉 EXPANDED ASSET GENERATION COMPLETE (NO TEXT)!');
      console.log(`⏱️  Total time: ${Math.round(totalTime/1000/60)} minutes`);
      console.log(`📊 Total assets attempted: ${totalAssets}`);
      console.log(`✅ Total completed: ${totalCompleted} assets`);
      console.log(`❌ Total failed: ${totalFailed} assets`);
      console.log(`📈 Success rate: ${Math.round(totalCompleted/totalAssets*100)}%`);
      console.log(`⚠️  VERIFIED: All images generated WITHOUT TEXT`);
      
      console.log('\\n📁 Generated assets saved to:');
      console.log('   - PNG images with specific dimensions (NO TEXT)');
      console.log('   - Specification files (.spec.json) for complex assets');
      console.log('   - Organized in expanded directory structure');
      console.log('   - Individual images for each design element');
      
    } catch (error) {
      console.error('💥 Expanded generation failed:', error);
      throw error;
    }
  }
}

// CLI interface
async function main() {
  const generator = new ExpandedAssetGenerator();
  const mode = process.argv[2] || 'all';
  const limit = process.argv[3] ? parseInt(process.argv[3]) : null;
  
  console.log(`🎯 Mode: ${mode.toUpperCase()}`);
  console.log(`⚠️  NO TEXT Policy: All images will be generated without any text or labels`);
  
  try {
    switch (mode) {
      case 'priority1':
        console.log('🎯 Running PRIORITY 1 assets (NO TEXT)');
        await generator.generateByPriority(1, limit);
        break;
      case 'priority2':
        console.log('📊 Running PRIORITY 2 assets (NO TEXT)');
        await generator.generateByPriority(2, limit);
        break;
      case 'priority3':
        console.log('🎨 Running PRIORITY 3 assets (NO TEXT)');
        await generator.generateByPriority(3, limit);
        break;
      case 'test':
        console.log('🧪 Running TEST mode (first 5 assets, NO TEXT)');
        await generator.generateByPriority(1, 5);
        break;
      case 'all':
      default:
        console.log('🌟 Running ALL EXPANDED ASSETS (NO TEXT)');
        await generator.generateAllAssets();
        break;
    }
  } catch (error) {
    console.error('💥 Asset generation failed:', error);
    process.exit(1);
  }
}

// Run if called directly
if (require.main === module) {
  main();
}

module.exports = { ExpandedAssetGenerator };